# Generated by Django 3.2.4 on 2021-07-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Images')),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
