# Generated by Django 3.2.4 on 2021-07-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_button_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
