# Generated by Django 3.2.4 on 2021-07-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_button_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='img',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
