# Generated by Django 3.2.4 on 2021-07-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_button_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='shop_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
