# Generated by Django 3.2.4 on 2021-07-01 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_button_shop_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Button',
            new_name='Menu',
        ),
    ]
