# Generated by Django 4.0.5 on 2022-06-27 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_payement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='des',
            field=models.CharField(max_length=200),
        ),
    ]
