# Generated by Django 4.0.5 on 2022-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_checkout1_alter_menu_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout1',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
