# Generated by Django 4.0.5 on 2022-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_checkout1_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout1',
            name='quantity',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
